language: node_js
node_js:
- '4'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  secure: DPTv9lkC9XJ+oCHMaLd8oWW9Lum8ZCSxts5Ltn8QSrA6+A/y9+B+8SUXWptL7RDA0MLno9JW/YBKoQjCNOSMKHlk5Deq2sjls52x/FkuqCGAUrv88nNgNU4tJYSE4Xgaqat4eSIKfxJEE3PIvRXmsmjputUiOPhjilA/6k8awAqIsWX3rS0z3ZPF1g2yA966z9JGFoKFG51lmkfKw+DxgjJi34Vw2/2tcd5J91SZcJxH9rrWJMsCM2f95a0Z3PFziyDEiXdcyyyM/sgJbyocKH+cfubznjFMODKagk8yHW1gWcMz//+6enn+9CuaCpThPtknqtRMZQYPYey0HU81Ks8FtEaWFAw+lwvwfBdWtQ0s3csKTRhbcDSNlcyq5ZwL7bDU8ByAryMUv6WGp4zGVEpEaPTToB1AILZbJVpSDjgiV9wwreQ319A/668TAVEGAhIiZ7Ihky+tVXoCdTpO74lBZY6IZjVkiBHjFNOLTuXAqMsKUgZQWvcx0yXWEgCKUTWAqrokksnJm95/4YuJrQI4CE/cL4OIE2lBCUTju6+Eq10NEAc+/k8TIMyiMovLhq3YuXPkBOSf53o6S5SqCYD59aQD/4coRjV9bfsBdpElZ6JijYJ7oU3nsuewSJ/35OXI6/7gwAyQXrpm+ejfuYNANBVNxtLEP8QTNHH0MRA=
